### ISSUE TITLE
JPEG2000DefaultDisplayResolutionBox no effect in metadata

### ISSUE THREAD

**Issue by devnullpointer** [faceless2/jpeg2000#1]
Hello, Have you been successful in getting correct  pixel/mm information in the metadata to be written with the file? I've created the JPEG2000DefaultDisplayResolutionBox node and all the childnodes (numerator/denominator/exponent) added it to the parent JPEG2000ResolutionBox/OptionalBoxes and set the tree from the parent node. The metadata prior to the image writers write(null, new IIOImage(image, null, imageMetaData), params) is correct, only when the image gets generated the pixel/mm is not set and GiMP is showing me 300dpi instead. I managed to get this working for all other formats (TIFF, JPG, PNG, BMP) but JP2 is a pain. I was wondering if your fork of the JAI library correctly writes resolution information with the metadata?

**Comment by faceless2** [comment]
We were parsing the display resolution boxes, but weren't doing anything with them. I've now added some methods to JPXReader and JPXWriter to retrieve and set resolution data.

I don't have Gimp here; I can't make Photoshop read a JP2 I've generated, but we're now writing the resolution information in exactly the same way as the way Photoshop writes it, so I'm reasonably confident it's correct.

I'm not quite sure I follow your problem. The values are stored in JP2 in pixels/meter, always - whether that's converted to pixels/inch in an application for display is not in anyone's control.  If you're seeing 300dpi then - I presume - _something_ is being set as the resolution. Whatever your issue, if you need to write resolution information as part of a JP2 file then I'm confident this codebase can now do it.

**Comment by faceless2** [comment]
A quick example showing the new methods:
```java
BufferedImage image = new BufferedImage(500, 500, BufferedImage.TYPE_INT_ARGB);
J2KWriter writer = new J2KWriter();
writer.setCompressionRatio(8, false);
writer.setCaptureResolution(11811, 11811); // 11811px/m = 300px/in (300dpi)
writer.setDisplayResolution(11811, 11811); // PhotoShop writes only "capture" resolution.
writer.setSource(image, 256);
writer.write(new FileOutputStream("out.jp2"));
```

**Comment by devnullpointer** [comment]
Actually I believe the 300dpi is a default value shown by GiMP when it can't find any resolution data. I'll try your latest build and see what results I get. Thanks.

**Comment by devnullpointer** [comment]
I apologize for the last question I don't think it merits its own issue, but must the src be built using jdk 1.5? If I set it to 1.6 I get 
```
compile:
    [javac] Compiling 52 source files to /home/local/FTI/kyriv/work/jpeg2000/target/classes/main
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 6
    [javac] warning: [options] source value 6 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.6 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] /home/local/FTI/kyriv/work/jpeg2000/src/main/java/jj2000/j2k/entropy/decoder/StdEntropyDecoder.java:625: error: cannot find symbol
    [javac]             System.runFinalizersOnExit(true);
    [javac]                   ^
    [javac]   symbol:   method runFinalizersOnExit(boolean)
    [javac]   location: class System
    [javac] /home/local/FTI/kyriv/work/jpeg2000/src/main/java/jj2000/j2k/entropy/encoder/EBCOTRateAllocator.java:226: error: cannot find symbol
    [javac]             System.runFinalizersOnExit(true);
    [javac]                   ^
    [javac]   symbol:   method runFinalizersOnExit(boolean)
    [javac]   location: class System
    [javac] /home/local/FTI/kyriv/work/jpeg2000/src/main/java/jj2000/j2k/entropy/encoder/StdEntropyCoder.java:961: error: cannot find symbol
    [javac]             System.runFinalizersOnExit(true);
    [javac]                   ^
    [javac]   symbol:   method runFinalizersOnExit(boolean)
    [javac]   location: class System
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some input files use unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 3 errors
    [javac] 4 warnings
```

**Comment by faceless2** [comment]
This source tree dates from Java 1.1 I believe - it's pretty crusty. You can remove those calls, they're only used for some dubious benchmarking code. And feel free to make a pull-request for the fix if you like!

**Comment by devnullpointer** [comment]
Sure thing, I'll set the code target to 1.8 and fix those calls (replaced by a shudown hook instead) and make the PR. But back to the issue, I generated a jp2 image and I'm still getting default resolutions, not the values I placed. I've compared the Exif info  of other images I used the JAI core library to set resolutions for and I get correct values for X, Y and Res Units, for the JP2 I still get default Exif values of 300 X and Y and Units set to inch.

**Comment by faceless2** [comment]
Well in that case I'm not sure, to be honest. If you're able to override the resolution in Gimp, save the file as a JP2 from Gimp then reload the file in Gimp and confirm it has the units you saved, then perhaps upload it somewhere and I'll take a look at it to see what they're expecting.

**Comment by devnullpointer** [comment]
Just checked with a proper JP2 tool and the resolution data is correct. Your original patch was good. I cosed the issue. I guess GiMP needs to work on their plugin a little more.... Thanks for your help.
