### ISSUE TITLE
JAI integration

### ISSUE THREAD

**Issue by rimmeraj** [faceless2/jpeg2000#2]
I am using jai-imageio-jpeg2000-1.3.0 with java's image.io framework and running into the black blob problem. Is there I way I can use your fixed version with image.io ?

**Comment by faceless2** [comment]
Not directly with imageio, no.

You can apply the patch easily enough yourself - it s a couple of lines. Or, you could consider modifying your code to check the first 8 bytes - if it's "00 00 00 0c 6a 50 20 20", divert away from imageio and load the BufferedImage using this version. It's easy enough to do, although what we really should have is a method on J2KReader that returns a BufferedImage. 

If that would be a solution for you let me know, I'll try to get it added in next week.

**Comment by rimmeraj** [comment]
> Not directly with imageio, no.
> 
> You can apply the patch easily enough yourself - it s a couple of lines. Or, you could consider modifying your code to check the first 8 bytes - if it's "00 00 00 0c 6a 50 20 20", divert away from imageio and load the BufferedImage using this version. It's easy enough to do, although what we really should have is a method on J2KReader that returns a BufferedImage.
> 
> If that would be a solution for you let me know, I'll try to get it added in next week.

I am trying to use it within the context of PDF box, so I am kind of stuck with the ImageIO style. I can code an ImageIO wrapper  using your version which I would require the BufferedImage, which would be the nice clean solution , just replace the jai-imageio-jpeg2000-1.3.0 version with yours. In the mean time could you point me to the patch. I would like to patch the current version to make sure it fixes the problem!

**Comment by faceless2** [comment]
As I recall the patch was this one: https://github.com/faceless2/jpeg2000/commit/b20342956ac5d05bb97522ddeb41e9bed5abfa95

**Comment by devnullpointer** [comment]
@faceless2 I could really use a method that returns a BufferedImage from the J2KReader. My current code:

```
final ImageInputStream iis = ImageIO.createImageInputStream(new ByteArrayInputStream(file.getContent()));
final J2KReader reader = new J2KReader(new J2KFile().read(new BEBufferedRandomAccessFile(destFile, "r", 8192)));
final ByteArrayInputStream data = new ByteArrayInputStream(reader.readAllBytes());
reader.close();
iis.close();
                
return ImageIO.read(data);
```
is returning null, even though the data object is full. I can provide you a jp2 file to test with if needed.
