### ISSUE TITLE
Add method to return BufferedImage in J2KReader

### ISSUE THREAD

**Issue by devnullpointer** [faceless2/jpeg2000#3]
As per your comment in #2 it would be great to have a method that returns a buffered image int he J2KReader class. Currently I'm only receiving null when I pass the byte data to ImageIO.read.

```
final ImageInputStream iis = ImageIO.createImageInputStream(new ByteArrayInputStream(file.getContent()));
final J2KReader reader = new J2KReader(new J2KFile().read(new BEBufferedRandomAccessFile(destFile, "r", 8192)));
final ByteArrayInputStream data = new ByteArrayInputStream(reader.readAllBytes());
reader.close();
iis.close();
                
return ImageIO.read(data);
```
is returning null, even though the data object is full. I can provide you a jp2 file to test with if needed.

**Comment by devnullpointer** [comment]
@faceless2 I tried to follow your test example reading the JP2 file and create a PNM then using the ImageIO to read the PNM bytes to create a BufferedImage. I always get "Empty region" exception. When I create a PNM file from another source using ImageIO and import it there are no issues.

```
java.lang.IllegalArgumentException: Empty region!
	at java.desktop/javax.imageio.ImageReader.computeRegions(ImageReader.java:2687)
	at com.github.jaiimageio.impl.plugins.pnm.PNMImageReader.read(PNMImageReader.java:298)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1468)
	at java.desktop/javax.imageio.ImageIO.read(ImageIO.java:1363)
	at com.fti.projectina.docuflex.common.client.ImageMetadata.createBufferedImageFromFile(ImageMetadata.java:198)

```

**Comment by faceless2** [comment]
I've added a new method, J2KReader.getBufferedImage(), which is pretty self descriptive. I can't speak for the PNM issue, but if you're still having issues with this JP2 file with the getBufferedImage method then by all means upload and and I'll take a look.

**Comment by faceless2** [comment]
I've added an example on the main page showing how to use this.

**Comment by devnullpointer** [comment]
@faceless2 is there a reason you are building on 1.5? When I run ant I get the error below. I tried moving to 1.6 but runFinalizersOnExit was removed on 1.6 so I'm kinda stuck.... 
```
Buildfile: /home/local/FTI/kyriv/work/local/jpeg2000/build.xml

compile:
    [javac] Compiling 52 source files to /home/local/FTI/kyriv/work/local/jpeg2000/target/classes/main
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 5
    [javac] error: Source option 5 is no longer supported. Use 6 or later.
    [javac] error: Target option 1.5 is no longer supported. Use 1.6 or later.

BUILD FAILED
/home/local/FTI/kyriv/work/local/jpeg2000/build.xml:12: Compile failed; see the compiler error output for details.

Total time: 0 seconds

```

**Comment by faceless2** [comment]
This code was originally written for Java 1.1 as I recall. I expect it's just never been migrated. The code that calls runFinalizersOnExit is never run - I've updated the code to remove the calls.

**Comment by devnullpointer** [comment]
You're a champ Mike!!

**Comment by devnullpointer** [comment]
Awesome. Works flawlessly!
